parameters:
  eye_on_hand: false
  freehand_robot_movement: false
  move_group: manipulator
  move_group_namespace: /
  namespace: /utra_realsense_handeyecalibration_eye_on_base/
  robot_base_frame: base_link
  robot_effector_frame: link_6
  tracking_base_frame: camera_color_frame
  tracking_marker_frame: camera_marker
transformation:
  qw: 0.699110041336382
  qx: -0.7139789502067729
  qy: -0.03831709684329698
  qz: -0.003317959279165115
  x: -0.02503728182743209
  y: -1.1770744541556073
  z: 0.23500818835776846
